version: '3.8'
services:
  vprodb:
    build: 
      context: ./docker-files/db
    image: nocnoc24/vpf_db
     Container_name:vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD =vprodpass
  vprocache01:
    image: "memcached"
    ports:
     - "11211:11211"
  vpromq01:
    image: rabbitmq
    ports:
     - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build: 
      context: ./docker-files/app
    image: nocnoc24/vpf_app
     Container_name:vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  vproweb:
    build: 
      context: ./docker-files/web
    image: nocnoc24/vpf_web
     Container_name:vproweb
    ports:
      - "80:80"
volumes:
   vprodbdata: {}
   vproappdata: {}





  

 
